//
//  IPMapDBConstants.h
//  MapProject
//
//  Created by innerpeacer on 15/10/26.
//  Copyright © 2015年 innerpeacer. All rights reserved.
//

#ifndef TYMapDBConstants_h
#define TYMapDBConstants_h

#define TABLE_CITY @"CITY"
#define TABLE_BUILDING @"BUILDING"
#define TABLE_MAPINFO @"MAPINFO"
#define TABLE_MAP_DATA @"MAPDATA"
#define TABLE_POI @"POI"
#define TABLE_MAP_SYMBOL_FILL_SYMBOL @"FILL_SYMBOL"
#define TABLE_MAP_SYMBOL_ICON_SYMBOL @"ICON_SYMBOL"

#define TABLE_ROUTE_LINK @"ROUTE_LINK"
#define TABLE_ROUTE_NODE @"ROUTE_NODE"

#define FIELD_CITY_0_PRIMARY_KEY @"_id"
#define FIELD_CITY_1_ID @"CITY_ID"
#define FIELD_CITY_2_NAME @"NAME"
#define FIELD_CITY_3_SNAME @"SNAME"
#define FIELD_CITY_4_LONGITUDE @"LONGITUDE"
#define FIELD_CITY_5_LATITUDE @"LATITUDE"
#define FIELD_CITY_6_STATUS @"STATUS"

#define FIELD_BUILDING_0_PRIMARY_KEY @"_id"
#define FIELD_BUILDING_1_CITY_ID @"CITY_ID"
#define FIELD_BUILDING_2_ID @"BUILDING_ID"
#define FIELD_BUILDING_3_NAME @"NAME"
#define FIELD_BUILDING_4_LONGITUDE @"LONGITUDE"
#define FIELD_BUILDING_5_LATITUDE @"LATITUDE"
#define FIELD_BUILDING_6_ADDRESS @"ADDRESS"
#define FIELD_BUILDING_7_INIT_ANGLE @"INIT_ANGLE"
#define FIELD_BUILDING_8_ROUTE_URL @"ROUTE_URL"
#define FIELD_BUILDING_9_OFFSET_X @"OFFSET_X"
#define FIELD_BUILDING_10_OFFSET_Y @"OFFSET_Y"
#define FIELD_BUILDING_11_STATUS @"STATUS"

#define FIELD_MAPINFO_0_PRIMARY_KEY @"_id"
#define FIELD_MAPINFO_1_CITY_ID @"CITY_ID"
#define FIELD_MAPINFO_2_BUILDING_ID @"BUILDING_ID"
#define FIELD_MAPINFO_3_MAP_ID @"MAP_ID"
#define FIELD_MAPINFO_4_FLOOR_NAME @"FLOOR_NAME"
#define FIELD_MAPINFO_5_FLOOR_NUMBER @"FLOOR_NUMBER"
#define FIELD_MAPINFO_6_SIZE_X @"SIZE_X"
#define FIELD_MAPINFO_7_SIZE_Y @"SIZE_Y"
#define FIELD_MAPINFO_8_XMIN @"XMIN"
#define FIELD_MAPINFO_9_YMIN @"YMIN"
#define FIELD_MAPINFO_10_XMAX @"XMAX"
#define FIELD_MAPINFO_11_YMAX @"YMAX"

#define FIELD_MAP_DATA_0_PRIMARY_KEY @"_id"
#define FIELD_MAP_DATA_1_OBJECT_ID @"OBJECT_ID"
#define FIELD_MAP_DATA_2_GEOMETRY @"GEOMETRY"
#define FIELD_MAP_DATA_3_GEO_ID @"GEO_ID"
#define FIELD_MAP_DATA_4_POI_ID @"POI_ID"
#define FIELD_MAP_DATA_5_FLOOR_ID @"FLOOR_ID"
#define FIELD_MAP_DATA_6_BUILDING_ID @"BUILDING_ID"
#define FIELD_MAP_DATA_7_CATEGORY_ID @"CATEGORY_ID"
#define FIELD_MAP_DATA_8_NAME @"NAME"
#define FIELD_MAP_DATA_9_SYMBOL_ID @"SYMBOL_ID"
#define FIELD_MAP_DATA_10_FLOOR_NUMBER @"FLOOR_NUMBER"
#define FIELD_MAP_DATA_11_FLOOR_NAME @"FLOOR_NAME"
#define FIELD_MAP_DATA_12_SHAPE_LENGTH @"SHAPE_LENGTH"
#define FIELD_MAP_DATA_13_SHAPE_AREA @"SHAPE_AREA"
#define FIELD_MAP_DATA_14_LABEL_X @"LABEL_X"
#define FIELD_MAP_DATA_15_LABEL_Y @"LABEL_Y"
#define FIELD_MAP_DATA_16_LAYER @"LAYER"
#define FIELD_MAP_DATA_17_LEVEL_MAX @"LEVEL_MAX"
#define FIELD_MAP_DATA_18_LEVEL_MIN @"LEVEL_MIN"


#define FIELD_POI_0_PRIMARY_KEY @"_id"
#define FIELD_POI_1_GEO_ID @"GEO_ID"
#define FIELD_POI_2_POI_ID @"POI_ID"
#define FIELD_POI_3_BUILDING_ID @"BUILDING_ID"
#define FIELD_POI_4_FLOOR_ID @"FLOOR_ID"
#define FIELD_POI_5_NAME @"NAME"
#define FIELD_POI_6_CATEGORY_ID @"CATEGORY_ID"
#define FIELD_POI_7_LABEL_X @"LABEL_X"
#define FIELD_POI_8_LABEL_Y @"LABEL_Y"
#define FIELD_POI_9_SYMBOL_ID @"SYMBOL_ID"
#define FIELD_POI_10_FLOOR_NUMBER @"FLOOR_NUMBER"
#define FIELD_POI_11_FLOOR_NAME @"FLOOR_NAME"
#define FIELD_POI_12_LAYER @"POI_LAYER"

#define FIELD_MAP_SYMBOL_FILL_0_PRIMARY_KEY @"_id"
#define FIELD_MAP_SYMBOL_FILL_1_SYMBOL_ID @"SYMBOL_ID"
#define FIELD_MAP_SYMBOL_FILL_2_FILL_COLOR @"FILL"
#define FIELD_MAP_SYMBOL_FILL_3_OUTLINE_COLOR @"OUTLINE"
#define FIELD_MAP_SYMBOL_FILL_4_LINE_WIDTH @"LINE_WIDTH"

#define FIELD_MAP_SYMBOL_ICON_0_PRIMARY_KEY @"_id"
#define FIELD_MAP_SYMBOL_ICON_1_SYMBOL_ID @"SYMBOL_ID"
#define FIELD_MAP_SYMBOL_ICON_2_ICON @"ICON"

#define FIELD_ROUTE_LINK_0_PRIMARY_KEY @"_id"
#define FIELD_ROUTE_LINK_1_LINK_ID @"LINK_ID"
#define FIELD_ROUTE_LINK_2_GEOMETRY @"GEOMETRY"
#define FIELD_ROUTE_LINK_3_LENGTH @"LENGTH"
#define FIELD_ROUTE_LINK_4_HEAD_NODE @"HEAD_NODE"
#define FIELD_ROUTE_LINK_5_END_NODE @"END_NODE"
#define FIELD_ROUTE_LINK_6_VIRTUAL @"VIRTUAL"
#define FIELD_ROUTE_LINK_7_ONE_WAY @"ONE_WAY"

#define FIELD_ROUTE_NODE_0_PRIMARY_KEY @"_id"
#define FIELD_ROUTE_NODE_1_NODE_ID @"NODE_ID"
#define FIELD_ROUTE_NODE_2_GEOMETRY @"GEOMETRY"
#define FIELD_ROUTE_NODE_3_VIRTUAL @"VIRTUAL"

#endif /* TYMapDBConstants_h */
