//
//  TYMapDBConstants.h
//  MapProject
//
//  Created by innerpeacer on 15/10/26.
//  Copyright © 2015年 innerpeacer. All rights reserved.
//

#ifndef TYMapDBConstants_h
#define TYMapDBConstants_h


#define TABLE_CITY @"CITY"
#define TABLE_BUILDING @"BUILDING"

#define TABLE_ROUTE_LINK @"ROUTE_LINK"
#define TABLE_ROUTE_NODE @"ROUTE_NODE"

#define FIELD_CITY_ID @"CITY_ID"
#define FIELD_CITY_NAME @"NAME"
#define FIELD_CITY_SNAME @"SNAME"
#define FIELD_CITY_LONGITUDE @"LONGITUDE"
#define FIELD_CITY_LATITUDE @"LATITUDE"
#define FIELD_CITY_STATUS @"STATUS"

#define FIELD_BUILDING_CITY_ID @"CITY_ID"
#define FIELD_BUILDING_ID @"BUILDING_ID"
#define FIELD_BUILDING_NAME @"NAME"
#define FIELD_BUILDING_LONGITUDE @"LONGITUDE"
#define FIELD_BUILDING_LATITUDE @"LATITUDE"
#define FIELD_BUILDING_ADDRESS @"ADDRESS"
#define FIELD_BUILDING_INIT_ANGLE @"INIT_ANGLE"
#define FIELD_BUILDING_ROUTE_URL @"ROUTE_URL"
#define FIELD_BUILDING_OFFSET_X @"OFFSET_X"
#define FIELD_BUILDING_OFFSET_Y @"OFFSET_Y"
#define FIELD_BUILDING_STATUS @"STATUS"


#define FIELD_ROUTE_LINK_0_PRIMARY_KEY @"_id"
#define FIELD_ROUTE_LINK_1_LINK_ID @"LINK_ID"
#define FIELD_ROUTE_LINK_2_GEOMETRY @"GEOMETRY"
#define FIELD_ROUTE_LINK_3_LENGTH @"LENGTH"
#define FIELD_ROUTE_LINK_4_HEAD_NODE @"HEAD_NODE"
#define FIELD_ROUTE_LINK_5_END_NODE @"END_NODE"
#define FIELD_ROUTE_LINK_6_VIRTUAL @"VIRTUAL"
#define FIELD_ROUTE_LINK_7_ONE_WAY @"ONE_WAY"

#define FIELD_ROUTE_NODE_0_PRIMARY_KEY @"_id"
#define FIELD_ROUTE_NODE_1_NODE_ID @"NODE_ID"
#define FIELD_ROUTE_NODE_2_GEOMETRY @"GEOMETRY"
#define FIELD_ROUTE_NODE_3_VIRTUAL @"VIRTUAL"

#endif /* TYMapDBConstants_h */
